"""Built-in scenario specs (dicts) covering Indian conditions across maps.
Each is a DSL dict consumable by dsl.build_from_dict."""

SPECS = {
 "two_wheeler_swarm": {"map": "narrow_street", "ego_speed": 5,
    "actors": [{"type": "two_wheeler", "path": "same", "s": 18, "lat": -1.5,
                "count": 6, "spread_s": 5},
               {"type": "auto", "path": "oncoming", "s": 40, "count": 2, "spread_s": 20}],
    "hazards": [{"type": "pothole", "count": 6}]},
 "auto_cutin": {"map": "narrow_street", "ego_speed": 6,
    "actors": [{"type": "auto", "path": "same", "s": 22, "lat": 2.2,
                "behavior": {"trigger_dist": 22, "trigger_lat": -1.4}},
               {"type": "two_wheeler", "path": "same", "s": 14, "count": 2}]},
 "slow_cart_block": {"map": "narrow_street", "ego_speed": 6,
    "actors": [{"type": "cart", "path": "same", "s": 26, "lat": -1.0},
               {"type": "two_wheeler", "path": "oncoming", "s": 40, "count": 3, "spread_s": 30}],
    "hazards": [{"type": "pothole", "count": 5}]},
 "cow_on_road": {"map": "narrow_street", "ego_speed": 6,
    "actors": [{"type": "cow", "path": "same", "s": 32, "lat": 0.2},
               {"type": "two_wheeler", "path": "same", "s": 18, "count": 2}]},
 "jaywalk_swarm": {"map": "narrow_street", "ego_speed": 6,
    "vrus": [{"cross_at": 45, "side": -1, "count": 3, "speed": 1.3, "trigger": 20, "spread": 3},
             {"cross_at": 50, "side": 1, "count": 2, "speed": 1.1, "trigger": 18}]},
 "child_dart": {"map": "narrow_street", "ego_speed": 6.5,
    "vrus": [{"cross_at": 40, "side": -1, "count": 1, "speed": 2.6, "trigger": 13, "radius": 0.25}]},
 "vendor_encroachment": {"map": "narrow_street", "ego_speed": 6,
    "hazards": [{"type": "encroach", "at": 45, "side": 1}],
    "vrus": [{"cross_at": 47, "side": 1, "count": 1, "speed": 1.0, "trigger": 20}]},
 "pothole_field": {"map": "narrow_street", "ego_speed": 7,
    "hazards": [{"type": "pothole", "count": 14}],
    "actors": [{"type": "two_wheeler", "path": "same", "s": 20, "count": 2}]},
 "speed_bumps": {"map": "narrow_street", "ego_speed": 8,
    "hazards": [{"type": "speedbump", "at": 30}, {"type": "speedbump", "at": 75},
                {"type": "speedbump", "at": 120}]},
 "monsoon_lowvis": {"map": "village_curvy", "ego_speed": 5,
    "environment": {"visibility": 0.45, "label": "monsoon"},
    "actors": [{"type": "auto", "path": "same", "s": 25, "count": 3, "spread_s": 20}],
    "vrus": [{"cross_at": 60, "side": 1, "count": 1, "speed": 1.0, "trigger": 14}]},
 "village_curvy_mixed": {"map": "village_curvy", "ego_speed": 5,
    "actors": [{"type": "auto", "path": "same", "s": 20, "count": 2, "spread_s": 25},
               {"type": "cart", "path": "same", "s": 60, "lat": -0.5}],
    "hazards": [{"type": "pothole", "count": 7}]},
 "junction_freeforall": {"map": "uncontrolled_junction", "ego_speed": 5,
    "actors": [{"type": "auto", "path": "cross_a", "s": 25, "count": 3, "spread_s": 18},
               {"type": "two_wheeler", "path": "cross_b", "s": 25, "count": 3, "spread_s": 18},
               {"type": "two_wheeler", "path": "oncoming", "s": 60, "count": 2, "spread_s": 40}]},
 "junction_cow_and_peds": {"map": "uncontrolled_junction", "ego_speed": 5,
    "actors": [{"type": "cow", "path": "same", "s": 80, "lat": 0.0}],
    "vrus": [{"cross_at": 75, "side": -1, "count": 2, "speed": 1.1, "trigger": 18, "spread": 4}]},
 "roundabout_yield": {"map": "roundabout", "ego_speed": 5,
    "actors": [{"type": "car", "path": "ring", "s": 20, "count": 3, "spread_s": 14}]},
 "arterial_dense": {"map": "arterial_4lane", "ego_speed": 10,
    "actors": [{"type": "car", "path": "l0", "s": 40, "count": 3, "spread_s": 25},
               {"type": "two_wheeler", "path": "l1", "s": 30, "count": 4, "spread_s": 18},
               {"type": "truck", "path": "onc0", "s": 80, "count": 2, "spread_s": 60}]},
 "arterial_biker_filter": {"map": "arterial_4lane", "ego_speed": 11,
    "actors": [{"type": "two_wheeler", "path": "l1", "s": 20, "lat": 0.0,
                "count": 6, "spread_s": 10}]},
 "highway_mixed": {"map": "highway", "ego_speed": 13,
    "actors": [{"type": "car", "path": "fast", "s": 60, "count": 2, "spread_s": 40},
               {"type": "truck", "path": "same", "s": 90, "count": 1}]},
 "highway_slow_intruder": {"map": "highway", "ego_speed": 15,
    "actors": [{"type": "cart", "path": "same", "s": 80, "lat": -1.0},
               {"type": "car", "path": "fast", "s": 40, "count": 2, "spread_s": 40}]},
 "highway_shoulder_ped": {"map": "highway", "ego_speed": 15,
    "vrus": [{"cross_at": 120, "side": -1, "count": 1, "speed": 1.4, "trigger": 25}]},
}
